export function formatDate(isoDate: string): string {
  const date = new Date(isoDate);
  return date.toLocaleDateString("en-US", {
    month: "short",   // "Jan", "Feb", ...
    day: "numeric",   // 1, 2, 3, ...
    year: "numeric",  // 2024, 2025, ...
  });
}
